freedombox/Plinth

actions/owncloud-setup

Fixes #87 and also does other minor improvements to owncloud action.  Commit messages contain more explanation.

Owncloud fixes

---

actions/xmpp
plinth/modules/xmpp/templates/xmpp.html
plinth/modules/xmpp/views.py

This fixes #167, and also adds the domainname and an example UID to the XMPP page, as discussed in #184.

XMPP polishes

---

actions/timezone-change
plinth/modules/config/config.py
plinth/modules/datetime/forms.py
plinth/modules/datetime/views.py

This is alternative implementation for #190 .  Bharath and I spoke to each other and agreed that I will explore a better solution.  This fix adds all miscellaneous time zones to the list.
It also moves the time zone setting to date/time module.

Handle default time zone properly

---

data/etc/apache2/conf-available/jwchat-plinth.conf
data/etc/apache2/sites-available/plinth.conf

Resolves Issue https://github.com/freedombox/Plinth/issues/171
"Update Apache auth config directives"

Changes Apache conf files to use Require instead of Allow/Deny

---

plinth/modules/restore/__init__.py
plinth/modules/restore/templates/restore_index.html
plinth/modules/restore/urls.py
plinth/modules/restore/views.py

- Missing comment added and comment styling.
- Expanded the description.
- Change the title and menu item capitalization for consistency.

restore: Fix minor styling issues

---

plinth/locale/nl/LC_MESSAGES/django.po

This NL translation is made, but not proofread. Use with caution :)

Added language NL translation

---

plinth/locale/nl/LC_MESSAGES/django.po

I missed one. Now translation should be complete.

Missing string added

---

actions/power
data/etc/plinth/modules-enabled/power
plinth/modules/power/__init__.py
plinth/modules/power/templates/power.html
plinth/modules/power/templates/power_reboot.html
plinth/modules/power/templates/power_shutdown.html
plinth/modules/power/urls.py
plinth/modules/power/views.py

There is now a power module under config, which has Shut Down and Reboot buttons.

Shutdown / Reboot Buttons

---

plinth/locale/da/LC_MESSAGES/django.po
plinth/locale/da/LC_MESSAGES/terms.org

Translate new and updated strings.
Fixes after proofreading and actual testing.

Update Danish .po from latest code.

---

plinth/modules/shaarli/views.py

please read https://github.com/freedombox/Plinth/issues/344

shaarli: on_install function

---

plinth/tests/test_network.py

Recently some parameters were added to network functions. This patch just fixes the existing tests.

Fix network tests

---

actions/dynamicdns

Fixes for various issues I have found when using especially in 'no NAT' scenario.
I believe we need to put in more effort into improving the quality of this important module.  @steglicd , I have feeling that we can simplify it somehow and avoid the trouble we currently going through.

Various Dynamic DNS Fixes

---

plinth/modules/dynamicdns/__init__.py
plinth/modules/dynamicdns/dynamicdns.py
plinth/modules/dynamicdns/templates/dynamicdns.html
plinth/modules/dynamicdns/templates/dynamicdns_status.html
plinth/modules/networks/networks.py

Feel free to cherry pick from these changes.

dynamicdns source string corrections

---

data/usr/lib/freedombox/setup.d/86_plinth
plinth/modules/roundcube/__init__.py
plinth/package.py
plinth/setup.py

Patch to run installation during initial setup using apt-get instead of PackageKit.
Also, a minor unrelated fix.

Setup with apt

---

actions/privoxy
plinth/modules/privoxy/__init__.py

This fixes #464 and seems more robust in case of default configuration changes in the privoxy package.

Set privoxy listen-address by debconf preseed before install.

---

plinth/modules/diagnostics/diagnostics.py

diagnostics: Don't run on modules not yet setup

---

actions/ldap

These were for issues that have now been fixed:
https://github.com/martymac/ldapscripts/issues/3
https://github.com/martymac/ldapscripts/issues/5

Clean up ldapscript workarounds

---

README.md

As mentioned in #753 , added a Debian badge

Added debian status image to README

---

plinth/modules/ejabberd/__init__.py
plinth/modules/ikiwiki/__init__.py
plinth/modules/ttrss/__init__.py

This should fix issue #699. I know it's almost outdated with the currently planned, more fine-grained user groups, but once they're implemented the sentences will have to be adapted just slightly.

ejabberd, ikiwiki, ttrss: user login descriptions, fixes #699

---

.travis.yml

Move CI notifications to new channel
