plinth/modules/users/templates/users_change_password.html, plinth/modules/users/views.py
Calling `form.save()` inside of `form_valid()` was missing;
Plus tiny cleanups like using SetPasswordForm instead of AdminPasswordChangeForm.
Note: 
This change allows any logged-in user to change all other user passwords.
I did this because 
- we don't have any other way to recover passwords via the GUI
- logged-in users can create other (potentially privileged) user accounts also.
=> bugfix: changing user password didn't work

plinth/modules/upgrades/templates/upgrades_run.html
tiny addition to #95:
This just hides the detailed output of 'unattended-upgrades'. The output is still available via a 'show details' button which toggles the output.
With javascript disabled the full details are shown right away.
=> More user-friendly output of an upgrade run

plinth/cfg.py, plinth/tests/data/plinth.config.with_missing_options, plinth/tests/data/plinth.config.with_missing_sections, plinth/tests/test_cfg.py, plinth/tests/test_context_processors.py, plinth/tests/test_menu.py
This commit adds three unit test modules to the codebase, the first in what is intended to be a series of test code submissions.  A new plinth/tests/data directory has also been added, to serve as a repository for miscellaneous test data.
Testing of cfg.py exposed two refactoring opportunities:
1. An explicit check was added to verify the existence of the secondary (non-default) plinth.config file.
2. The configparser.SafeConfigParser class was replaced with configparser.ConfigParser to resolve a DeprecationWarning.  
Note: Two tests in test_menu.py have had to be marked as skipped, and kvstore.py could not be tested at all, since they seem to require Django to be running and configured prior to initiation of the 'test' command.  If anyone can suggest a (hopefully lightweight) solution or …
=> Updated: Unit tests (#1)

actions/owncloud-setup
Restarting Apache breaks existing connections.  This includes the connection
on which the Plinth's user has made the ownCloud enable/disable request.  This
leads to an almost certain 'Connection Interupted' message to the client when
changes to ownCloud are submitted.
On the other hand, 'reload' is sufficient and 'restart' is not required.  It is
also faster and recommended by 'a2enconf' and 'a2disconf' commands.
=> owncloud: Do Apache reload instead of restart

actions/dynamicdns, plinth/modules/dynamicdns/dynamicdns.py, plinth/modules/dynamicdns/templates/dynamicdns.html, plinth/modules/dynamicdns/templates/dynamicdns_configure.html
Would be nice if freedombox could be reached via DNS resolved hostname (even if freedombox is connected via dynamic IP).
For this reason I'm implementing a ez-ipupdate module.
The module should detect the current WAN IP (even if freedombox is connected behind NAT router) and push the IP to a open source GnudIP server if a change is detected.
IPv6 and other Server types than gnudip should also be included later.
GnudIP vs. update URL:
* Gnudip is more safe (md5 hashed and salted password transmission prevent replay attacks)
* update URL is more generic (the most common dynamic DNS Service provides a URL to update the IP)
=> dynamicdns

.travis.yml, plinth/tests/coverage/coverage.py, plinth/tests/test_context_processors.py, plinth/tests/test_menu.py, requirements.txt, setup.py
This pull request includes file additions and modifications to enable the integration of Plinth installation and testing with Travis-CI (https://travis-ci.org/).
- Add file .travis.yml as the Travis configuration file for the project.
- Add file requirements.txt to specify project package dependencies to be installed via pip.
- In setup.py, remove 'pygobject' from, and add 'pyyaml' to, the install_requires argument.
- In setup.py, rename module plinth.tests.coverage.test_coverage to coverage.
- In setup.py, rename class plinth.tests.coverage.coverage.TestCoverageCommand to CoverageCommand.
- Add file \_\_init\_\_.py to allow builds under Python 3.2.
- Rename file plinth/tests/coverage/test_coverage.py to coverage.py.
- In plinth/tests/coverage/coverage.py, rename class TestCoverageCommand …
=> Enable integration of Plinth with Travis-CI

data/etc/plinth/plinth.config, data/lib/systemd/system/plinth.service, plinth/__main__.py, plinth/cfg.py, setup.py
- When running in an environment without systemd, the changes are completely
ignored.
- When running under systemd, the patch introduces a systemd native service
file to take advantages of nice feature provided by systemd.
- One of the feature currently taken advantage of is the ability to restart the
service automatically if it ever crashes or exits with error.
- Another feature is that when we wish to kill Plinth all the processes under
the cgroup are killed as well.
=> Add systemd service file

plinth/templates/base.html
I suggest the following changes to fix #134:
1. Add a Log out button to the right of the user dropdown menu. Hide the button using javascript (if enabled). So the button will only be shown when javascript is disabled.
2. Add a link from the user dropdown button to the user's edit page. If javascript is enabled, the button will function as a dropdown menu, otherwise it is just a link.
=> Fixes for user dropdown menu when javascript is disabled

.travis.yml, INSTALL, data/etc/plinth/modules-enabled/networks, plinth/modules/networks/networks.py, plinth/network.py, requirements.txt, setup.py
This fixes #124.  This pull request makes Plinth use libnm (introduced with network-manager 1.0) with gobject-introspection instead of python-networkmanager.  The reasons have been highlighted in original issue.  Since all the required dependencies are now avialable, this pull request also enables networks modules.
There is one known issue: trying to retrieve ip_address during edit connection results in a segfault.  This is most likely an issue with python3-gi or libnm.  So, for now, showing earlier set IP address has been disabled.  Setting a new one works.  I believe we can still merge this with this small issue present.
=> Network manager glib

actions/deluge, plinth/modules/deluge/templates/deluge.html, plinth/modules/deluge/urls.py, plinth/modules/deluge/views.py
To manage starting and stopping processes that don't provide init scripts, we could use systemd.  This pull request automatically manages starting/stoping deluge-web using systemd.
=> deluge: Auto start deluge-web using systemd

plinth/__main__.py
Small devices like the raspberry pi end up eating a number of resources (~20%
of the CPU according to top, even more if something else is increasing the
load, together with tor they eat ~70% of the cpu "on idle" ~50% for plinth
and ~20% for tor) stat the files once per second.
=> Use the cherrypy autoreload feature only in debug mode

actions/tor, plinth/modules/tor/tor.py, plinth/package.py
This pull request sets up Tor after installation instead of in freedombox-setup.  We can now remove Tor code from freedomxbox-setup.
Also enabled IPv6 for Tor.
Minor fix during packages installation.
=> Tor setup in Plinth instead of freedombox-setup

actions/xmpp
This is a simple work around to fix #239.
=> xmpp: Disable TLS on http-bind port

.travis.yml
@BobGirard , you are right about latest version of coverage causing the problem.  However, instead of upgrading Python version (which is still not possible for us unfortunately), I have installed particular coverage version.  Please review this change.
This patch installs coverage 3.7 instead of latest coverage 4.0 on
Travis before a build. Coverage 4.0 does not support Python 3.2.  Due to
need for system-installed, python-dependency packages and due to Travis
infrastructure using Ubuntu 12.04, we can only build on Python 3.2 in
Travis.
=> Require older version of coverage for Travis build

actions/pagekite
When initializing Augeas make sure that it only loads the pagekite lens with its corresponding files so that Pagekite page loads are much faster.
=> pagekite: Make Augeas loading narrower and faster

README.md
Removes erroneous first line and adds links to Plinth wiki and Freedombox homepage.
=> fixes #263

actions/restore, data/etc/plinth/modules-enabled/restore, plinth/modules/restore/__init__.py, plinth/modules/restore/forms.py, plinth/modules/restore/templates/restore_index.html, plinth/modules/restore/urls.py, plinth/modules/restore/views.py
reStore is a server for unhosted web applications (https://unhosted.org/). The idea is to uncouple web applications from the data, and thus the data can be stored on any unhosted storage server.
reStore does not support ldap, so freedombox users have to create an account via the web interface that comes with the reStore package.
=> Added reStore module/application

plinth/modules/config/config.py
Validator now allows hyphens in middle of string for both Domain names and Host names.
=> Allow hyphens in hostname and domainname. Fixes #275.

plinth/__main__.py, plinth/modules/config/config.py, plinth/modules/config/tests/test_config.py
- The language choice is stored within the session, not persistently (in kvstore)
- This removes confirmation messages if nothing was changed
Maybe there is a better way to detect the plinth / locale directory than this:
https://github.com/fonfon/Plinth/blob/language-detect/plinth/__main__.py#L218
If a user chooses a certain language his setting survives login/logout with the same browser, but won't survive using another browser or device. Thus we should use kvstore in the long run to store user language choices.
=> Adds a 'language' dropdown field to the system configuration

actions/quassel, data/etc/plinth/modules-enabled/quassel, data/usr/lib/firewalld/services/quassel-plinth.xml, plinth/modules/quassel/__init__.py, plinth/modules/quassel/forms.py, plinth/modules/quassel/templates/quassel.html, plinth/modules/quassel/urls.py, plinth/modules/quassel/views.py
This is a module that simply installs and configures quassel-core.
I included a firewalld service file for quassel in this patch. If it gets merged into firewalld (https://github.com/t-woerner/firewalld/pull/58), then it can be removed from plinth.
=> Quassel IRC module

plinth/modules/config/config.py, plinth/modules/power/__init__.py
This fixes 2 remaining issues of #347.
=> Use ugettext_lazy during init of config and power modules.

plinth/modules/first_boot/templates/firstboot_navbar.html, plinth/modules/first_boot/templates/firstboot_state0.html, plinth/modules/first_boot/templates/firstboot_state1.html, plinth/modules/first_boot/templates/firstboot_state10.html
This pull request is originally from @fonfon . I made some modifications.  This pull request should be merged only after tagging 0.7.2.
Here are some comments/updates on @fonfon 's proposal.
- Brand should not be shown in state0 but should be shown state1.
- Applications icon should not be shown in state0 and state1.
- 'Start Setup' is better than 'Next'.
- Removing congratulations and pushing the basic details message down are good in state0.
- In the final page, you are right about the confusion with the two buttons.  However, instead of removing, I placed one button in one section and another button in another section.
- Fixed issue with {{ cfg.box_name }} and `blocktrans` tag.
- Chaging 'Network Configuration' to 'Current Network Configuraion' is nice.
=> First boot improvements

plinth/modules/networks/forms.py, plinth/modules/networks/networks.py, plinth/network.py
- Make connection adding/editing forms inherit from base.
- Make the forms responsible for extracting cleaned data.
- Use dictionaries for passing around settings values while
adding/editing connections.
Having written most of the original code, @steglicd can review this patch (if he chooses to).
=> networks: Refactor for simplicity and brevity

actions/letsencrypt, data/etc/plinth/modules-enabled/letsencrypt, plinth/modules/letsencrypt/__init__.py, plinth/modules/letsencrypt/templates/letsencrypt.html, plinth/modules/letsencrypt/urls.py, plinth/modules/letsencrypt/views.py
This is the first implementation for obtaining certificates from Let's
Encrypt.  Following the features and limitations.
- Requires manual operation.
- Registrations are done anonymously.
- Supports revoking and re-obtaining certificates.  Does not have a way
to show if a certficate is already renewed.
- Automatic renewal is not available.
- Details messages in case of errors.
- Has ability to switch to testing mode by using LE's staging servers.
- Sets up Apache configuration for the domain and enables/disables it.
When certificates are not available for a domain, default website
configuration is used.  When certificates are available, separate
SSL website configuration for each domain is used.
- Many domain will work with a single IP address with the help of Server
Name Indication (SNI) …
=> letsencrypt: New basic module for SSL certficates

.travis.yml
pgi 0.0.11.1 does not build successfully however 0.0.10.1 works.
Reported upstream issue https://github.com/lazka/pgi/issues/31.
Meanwile, to fix the builds, depend on older version.
=> travis: Require a specific version of pgi for fixing build

data/etc/ikiwiki/plinth-blog.setup, data/etc/ikiwiki/plinth-wiki.setup
These files are not executed directly, but through ikiwiki's setup command. Remove these lines to correct 2 lintian warnings.
=> Remove #! sequence from ikiwiki setup automators.

data/usr/lib/freedombox/setup.d/86_plinth
Start DBus daemon to ensure PackageKit can use it.  Only start if it is
not already running.  Stop after setup.  Stop only if we have started
it.
I have done some manual unit testing on the patch.  However, i have not tested with either full image or installing through Debian package.  Not sure if I will get the time to do it in next few days.  I could use some help doing this.
=> Run Plinth setup during FreedomBox setup

actions/users
These values were copied from freedombox-setup, but we need to drop the quotes. Otherwise nslcd cannot find the LDAP server.
I built an image with this change patched in, and confirmed that the user's edit page can now be accessed, and the user can login through console or SSH.
=> Fix quoted values in nslcd config

Vagrantfile
- Use vagrant box from https://atlas.hashicorp.com/freedombox/boxes/plinth-dev
- v0.9.0 box for virtualbox provider has been uploaded.
- This was converted from FreedomBox 0.9 virtualbox-amd64 image.
- Used latest freedom-maker script, so it uses contrib but not non-free.
=> Switch to official vagrant box

plinth/modules/letsencrypt/__init__.py
There is an on-going discussion regarding whether the certbot (letsencrypt) package should be in Debian stretch, due to instability of the API:
https://lists.debian.org/debian-devel/2016/11/msg00784.html
With this change, the certbot package won't be a dependency for plinth, and won't be installed automatically. Users can still visit the letsencrypt page to setup the module, which will install the certbot package (assuming the package is available).
=> letsencrypt: Mark module as non-essential

data/etc/apache2/includes/freedombox-single-sign-on.conf
- Solves bug #890
- Since Apache might be started before Plinth setup is ever run, we
have to handle the case where the auth_pubtkt module may not be available.
=> SSO: Add check to see if auth_pubtkt module is available

actions/networks, plinth/modules/networks/__init__.py
Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>
This is the last piece required after #1002, that will let us eliminate freedombox-setup's first-run and the reboot after it.  Since the networks module's version is not incremented, users upgrading from earlier version of Plinth will never run the setup code.  However, images built with the change will end up running the setup code.
Work remaining here is to test.
=> [WIP] networks: Move initial connection setup to Plinth

actions/networks
When network-manager restarts, it leaves the existing connections intact. So, active the newly created connection to make them work.
Only add a connection for a device if a connection with that name is not already
associated with that device.
Closes #1045.
Minimal testing was done to ensure the results are better than what we have now.  May check again later with full disk image but I think the patch can be merged.
=> networks: activate connection properly and idempotancy for setup
